slides:
	pandoc -t beamer \
               --latex-engine=xelatex \
               -V theme:metropolis \
	       --variable classoption="aspectratio=169" \
               -o slides.pdf \
               slides.md
